/**
 * bagrut-curriculum.ts — the canonical bagrut curriculum mapping.
 *
 * Source of truth: the official Ministry of Education syllabus for math5
 * (שאלון 806 = שאלון 581, ושאלון 807 = שאלון 582), 2024-2025 curriculum.
 *
 * Why this exists:
 *  - The student opens the app and wants to feel "this is exactly my
 *    bagrut, in the right order".
 *  - Every lesson page needs to say "this is from שאלון 581, worth
 *    20-25 points, appears in every bagrut".
 *  - The picker should group by paper with section headers.
 *  - The default plan generated by onboarding should be in the right
 *    pedagogical order.
 *
 * ============================================================
 * OFFICIAL SYLLABUS REFERENCE — for content authors
 * ============================================================
 *
 * שאלון 581 (806) contains:
 *   - אלגברה:    אלגברה בסיסית, גיאו׳ אנליטית בסיסית, משוואות
 *                ואי-שוויונות (כל הסוגים), סדרות, הסתברות,
 *                בעיות מילוליות (תנועה, הספק ועבודה).
 *   - גיאו׳ + טריגו: גיאומטריה אוקלידית (חפיפה, דמיון, תאלס,
 *                מצולעים, מעגלים, פרופורציה במעגל),
 *                טריגונומטריה במישור (סינוסים, קוסינוסים,
 *                זהויות, פתרון משולשים).
 *   - חדו"א:      חשבון דיפרנציאלי + אינטגרלי של פולינום /
 *                רציונלית / שורש / ערך מוחלט / טריגונומטרית,
 *                בעיות קיצון.
 *
 * שאלון 582 (807) contains:
 *   - אלגברה:    חזרה על חזקות ושורשים, מעריכיות, לוגריתמיות,
 *                משוואות ואי-שוויונות מעריכיים/לוגריתמיים,
 *                בעיות גידול ודעיכה, מספרים מרוכבים.
 *   - גיאו׳ אנליטית: ישר, מעגל, פרבולה, אליפסה, מקומות גיאומטריים.
 *   - טריגו׳ במרחב: משפט שלושת האנכים, חישובי זוויות וגופים
 *                (תיבה, מנסרה, פירמידה).
 *   - וקטורים:    במישור ובמרחב, מכפלה סקלרית, ישר ומישור.
 *   - חדו"א:      פונקציות מעריכיות (כולל $e$), לוגריתמיות,
 *                שורש, טריגונומטריות.
 *
 * ============================================================
 * GAPS — content the app does NOT yet have
 * ============================================================
 *
 *  - גיאומטריה אוקלידית (581) — חסר שיעור לחלוטין
 *  - בעיות מילוליות (581) — חסר שיעור (תנועה, הספק ועבודה)
 *  - טריגונומטריה במרחב (582) — חסר שיעור (שלושת האנכים, גופים)
 *  - גאומ׳ אנליטית של פרבולה ואליפסה (582) — קיים רק ישר ומעגל
 *  - וקטורים במישור (582) — קיים רק במרחב
 *
 * סטטיסטיקה (התפלגות נורמלית) — לא מופיע בסילבוס 807/582 העדכני.
 *   מסומן כ-out-of-scope בקוד מטה, אבל השיעור נשמר לשימוש עתידי.
 */

export type BagrutPaper = '581' | '582';

/** How "core" the topic is — affects visual emphasis in the UI. */
export type TopicWeight = 'core' | 'standard' | 'optional' | 'foundational' | 'out-of-scope';

/** Frequency of appearance in actual bagruyot — short Hebrew phrase. */
export type AppearsIn =
  | 'בכל בגרות'
  | 'ברוב הבגרויות'
  | 'בכמחצית מהבגרויות'
  | 'אופציונלי'
  | 'מחוץ לסילבוס';

export type TopicMapping = {
  /** Topic key — must match the topic name registered in lessons/index.ts. */
  key: string;
  /** Hebrew display name (usually identical to `key`). */
  displayName: string;
  /** Short emoji for the topic — matches existing /quiz pickers. */
  emoji: string;
  /** Primary bagrut paper. */
  paper: BagrutPaper;
  /** Whether the topic also appears in the other paper. */
  alsoIn?: BagrutPaper;
  /** Visual emphasis. */
  weight: TopicWeight;
  /** How often it appears in real bagruyot. */
  appearsIn: AppearsIn;
  /** Typical point value when it does appear (a question is 20-25 pts). */
  typicalPoints: string;
  /** One-line description of how the topic is examined. */
  examStyle: string;
  /** Optional clarifying note about how the topic appears officially —
   *  e.g. "תת-נושא של אלגברה בסילבוס הרשמי", "לא נושא רשמי". */
  officialNote?: string;
};

// ---------------------------------------------------------------------------
// שאלון 581 (806) — אלגברה, גיאו׳ אוקלידית + טריגו, חדו"א של פונקציות אלגבריות
// ---------------------------------------------------------------------------
const PAPER_581: TopicMapping[] = [
  {
    key: 'אלגברה',
    displayName: 'אלגברה',
    emoji: '🔣',
    paper: '581',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '15-25',
    examStyle:
      'משוואות ריבועיות עם פרמטר, אי-שוויונות, רדיקלים, רציונליות. בסיס לכל שאר השאלון.',
  },
  {
    key: 'סדרות',
    displayName: 'סדרות',
    emoji: '⋯',
    paper: '581',
    weight: 'core',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '15-25',
    examStyle:
      'חשבונית/הנדסית, סכומים סופיים ואינסופיים, נוסחת נסיגה, ריבית דריבית.',
    officialNote: 'בסילבוס הרשמי — תת-נושא של "אלגברה" בשאלון 581.',
  },
  {
    key: 'הסתברות',
    displayName: 'הסתברות',
    emoji: '🎲',
    paper: '581',
    weight: 'core',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '15-25',
    examStyle:
      'הסתברות מותנית, נוסחת בייס, בינומי, עץ הסתברויות, קומבינטוריקה.',
    officialNote: 'בסילבוס הרשמי — תת-נושא של "אלגברה" בשאלון 581.',
  },
  {
    key: 'פונקציות',
    displayName: 'פונקציות (יסודות)',
    emoji: '📈',
    paper: '581',
    alsoIn: '582',
    weight: 'foundational',
    appearsIn: 'בכל בגרות',
    typicalPoints: '—',
    examStyle:
      'יסודות חקירה — תחום הגדרה, חיתוכים, אסימפטוטות. מקדים את חדו"א בשני השאלונים.',
    officialNote:
      'לא נושא רשמי בסילבוס — מקדים פדגוגי לפני שיעורי חדו"א.',
  },
  {
    key: 'טריגונומטריה',
    displayName: 'טריגונומטריה',
    emoji: '🔺',
    paper: '581',
    alsoIn: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle:
      'במישור (581): סינוסים, קוסינוסים, זהויות, פתרון משולשים. במרחב (582): שלושת האנכים, גופים — חסר.',
  },
  {
    key: 'חשבון דיפרנציאלי',
    displayName: 'חשבון דיפרנציאלי',
    emoji: '∂',
    paper: '581',
    alsoIn: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle:
      'נגזרות, חקירה, קיצון. ב-581: פולינום/רציונלית/שורש/ערך מוחלט/טריגו. ב-582: מעריכית/ln.',
  },
  {
    key: 'חשבון אינטגרלי',
    displayName: 'חשבון אינטגרלי',
    emoji: '∫',
    paper: '581',
    alsoIn: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle:
      'שטח, נפח סיבוב, אינטגרציה בהצבה. בכל שאלון — משפחות פונקציות שונות.',
  },
];

// ---------------------------------------------------------------------------
// שאלון 582 (807) — מעריכית/ln, גיאו׳ אנליטית, וקטורים, מרוכבים
// ---------------------------------------------------------------------------
const PAPER_582: TopicMapping[] = [
  {
    key: 'פונקציה מעריכית',
    displayName: 'פונקציה מעריכית',
    emoji: '📊',
    paper: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle:
      'גידול ודעיכה, $e^x, a^x$, פתרון משוואות מעריכיות, חצי חיים, מציאת בסיס/זמן.',
  },
  {
    key: 'פונקציית ln',
    displayName: 'פונקציית ln',
    emoji: '🧮',
    paper: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle:
      'חוקי לוגריתם, נגזרת ואינטגרל של $\\ln$, חקירת פונקציות לוגריתמיות.',
  },
  {
    key: 'גאומטריה אנליטית',
    displayName: 'גאומטריה אנליטית',
    emoji: '📍',
    paper: '582',
    weight: 'core',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '20-25',
    examStyle:
      'ישר, מעגל, פרבולה, אליפסה — משוואות קנוניות, משיקים, מקומות גיאומטריים. (פרבולה+אליפסה — חסר תוכן.)',
  },
  {
    key: 'וקטורים במרחב',
    displayName: 'וקטורים במרחב',
    emoji: '➡️',
    paper: '582',
    weight: 'core',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '20-25',
    examStyle:
      'מכפלה סקלרית/וקטורית, ישר ומישור במרחב, חישובים, משפט שלושת האנכים.',
  },
  {
    key: 'מספרים מרוכבים',
    displayName: 'מספרים מרוכבים',
    emoji: 'ℂ',
    paper: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '15-25',
    examStyle:
      'הצגה אלגברית/קוטבית, דה-מואבר, שורשי יחידה, מישור גאוס, מקומות גיאומטריים, סדרות מרוכבים.',
  },
  {
    key: 'סטטיסטיקה',
    displayName: 'סטטיסטיקה',
    emoji: '📉',
    paper: '582',
    weight: 'out-of-scope',
    appearsIn: 'מחוץ לסילבוס',
    typicalPoints: '—',
    examStyle:
      'התפלגות נורמלית, מרווח סמך. לא בסילבוס 807 העדכני — נשמר כתוכן רזרבי.',
    officialNote:
      'אינו מופיע בסילבוס 807/582 העדכני. נשמר באפליקציה כי הוא רלוונטי לתלמידים שלמדו לפי תכנית קודמת.',
  },
];

/**
 * Canonical curriculum — שאלון 581 first (algebra is the foundation),
 * then 582. Within each paper, ordered pedagogically:
 *   - 581: algebra → sequences → probability → functions intro → trig → calculus
 *   - 582: exponential → ln → analytic geo → vectors → complex → statistics (out of scope)
 */
export const MATH5_CURRICULUM: TopicMapping[] = [...PAPER_581, ...PAPER_582];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Lookup the curriculum entry for a given topic. */
export function getTopicMapping(topic: string): TopicMapping | null {
  return MATH5_CURRICULUM.find((t) => t.key === topic) ?? null;
}

/** All topics belonging to a paper, in canonical order. */
export function topicsByPaper(paper: BagrutPaper): TopicMapping[] {
  return MATH5_CURRICULUM.filter((t) => t.paper === paper);
}

/** Returns the canonical index (0-based) of a topic in the curriculum.
 *  Useful for sorting any user-defined list back into bagrut order. */
export function curriculumIndex(topic: string): number {
  const i = MATH5_CURRICULUM.findIndex((t) => t.key === topic);
  return i === -1 ? Infinity : i;
}

/** Short label like "שאלון 581" — used by the BagrutBadge component. */
export function paperLabel(paper: BagrutPaper): string {
  return `שאלון ${paper}`;
}
