/**
 * bagrut-curriculum.ts — the canonical bagrut curriculum mapping.
 *
 * Every place in the app that lists math5 topics (picker, study plan,
 * onboarding, lesson page) should consume this module instead of
 * hard-coding its own order or labels. The data here reflects the
 * official Ministry of Education syllabus for math5 (שאלון 581 + 582)
 * and the empirical breakdown of point weights based on bagrut exams
 * from 2020-2025.
 *
 * Why this exists:
 *  - The student opens the app and wants to feel "this is exactly my
 *    bagrut, in the right order".
 *  - Every lesson page needs to say "this is from שאלון 581, worth
 *    20-25 points, appears in every bagrut".
 *  - The picker should group by paper with section headers.
 *  - The default plan generated by onboarding should be in the right
 *    pedagogical order (שאלון 581 first because it's the foundation).
 */

export type BagrutPaper = '581' | '582';

/** How "core" the topic is — affects visual emphasis in the UI. */
export type TopicWeight = 'core' | 'standard' | 'optional';

/** Frequency of appearance in actual bagruyot — short Hebrew phrase. */
export type AppearsIn = 'בכל בגרות' | 'ברוב הבגרויות' | 'בכמחצית מהבגרויות' | 'אופציונלי';

export type TopicMapping = {
  /** Topic key — must match the topic name registered in lessons/index.ts. */
  key: string;
  /** Hebrew display name (usually identical to `key`). */
  displayName: string;
  /** Short emoji for the topic — matches existing /quiz pickers. */
  emoji: string;
  /** Primary bagrut paper. */
  paper: BagrutPaper;
  /** Whether the topic also appears in the other paper (rare). */
  alsoIn?: BagrutPaper;
  /** Visual emphasis. */
  weight: TopicWeight;
  /** How often it appears in real bagruyot. */
  appearsIn: AppearsIn;
  /** Typical point value when it does appear (a question is 20-25 pts). */
  typicalPoints: string;
  /** One-line description of how the topic is examined. */
  examStyle: string;
};

// ---------------------------------------------------------------------------
// שאלון 581 — אלגברה, פונקציות פולינומיות/רציונליות, אנליזה, גיאומטריה, וקטורים
// ---------------------------------------------------------------------------
const PAPER_581: TopicMapping[] = [
  {
    key: 'אלגברה',
    displayName: 'אלגברה',
    emoji: '🔣',
    paper: '581',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '15-25',
    examStyle: 'משוואות ריבועיות עם פרמטר, אי-שוויונים, ערך מוחלט, רדיקלים. תמיד שאלה אחת לפחות.',
  },
  {
    key: 'פונקציות',
    displayName: 'פונקציות',
    emoji: '📈',
    paper: '581',
    alsoIn: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle: 'חקירת פונקציה רציונלית/פולינומית — תחום הגדרה, אסימפטוטות, קיצון, תחומי עלייה/ירידה.',
  },
  {
    key: 'חשבון דיפרנציאלי',
    displayName: 'חשבון דיפרנציאלי',
    emoji: '∂',
    paper: '581',
    alsoIn: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle: 'נגזרות, משיק, קיצון, בעיות אופטימיזציה יישומיות. הבסיס לחקירת פונקציות.',
  },
  {
    key: 'חשבון אינטגרלי',
    displayName: 'חשבון אינטגרלי',
    emoji: '∫',
    paper: '581',
    alsoIn: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle: 'אינטגרלים, שטחים בין גרפים, נפח גוף סיבוב. לרוב סעיף בחקירת פונקציה.',
  },
  {
    key: 'סדרות',
    displayName: 'סדרות',
    emoji: '⋯',
    paper: '581',
    weight: 'standard',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '15-20',
    examStyle: 'חשבונית/הנדסית, סכום, ריבית דריבית, שאלות מילוליות עם סדרה.',
  },
  {
    key: 'גאומטריה אנליטית',
    displayName: 'גאומטריה אנליטית',
    emoji: '📍',
    paper: '581',
    weight: 'standard',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '20-25',
    examStyle: 'ישר ומעגל — חיתוכים, משיקים, מרחקים, הוכחות גאומטריות אלגבריות.',
  },
  {
    key: 'וקטורים במרחב',
    displayName: 'וקטורים במרחב',
    emoji: '➡️',
    paper: '581',
    weight: 'standard',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '15-25',
    examStyle: 'מכפלה סקלרית/וקטורית, ישר/מישור במרחב, מרחקים, זוויות.',
  },
];

// ---------------------------------------------------------------------------
// שאלון 582 — פונקציות טרנסצנדנטיות, הסתברות, סטטיסטיקה, מרוכבים
// ---------------------------------------------------------------------------
const PAPER_582: TopicMapping[] = [
  {
    key: 'פונקציה מעריכית',
    displayName: 'פונקציה מעריכית',
    emoji: '📊',
    paper: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle: '$e^x, a^x$ — חקירה, גדילה ודעיכה אקספוננציאלית, פתרון משוואות עם הצבה.',
  },
  {
    key: 'פונקציית ln',
    displayName: 'פונקציית ln',
    emoji: '🧮',
    paper: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle: 'לוגריתם טבעי — חקירה, נגזרות עם שרשרת, אינטגרל $\\ln$, חוקי לוגריתם.',
  },
  {
    key: 'טריגונומטריה',
    displayName: 'טריגונומטריה',
    emoji: '🔺',
    paper: '582',
    weight: 'core',
    appearsIn: 'בכל בגרות',
    typicalPoints: '20-25',
    examStyle: 'זהויות, משוואות, חקירת $\\sin/\\cos$, נגזרות ואינטגרלים טריגונומטריים.',
  },
  {
    key: 'הסתברות',
    displayName: 'הסתברות',
    emoji: '🎲',
    paper: '582',
    weight: 'standard',
    appearsIn: 'ברוב הבגרויות',
    typicalPoints: '20-25',
    examStyle: 'הסתברות מותנית, בייס, בינומי, תוחלת ושונות, עץ הסתברויות.',
  },
  {
    key: 'סטטיסטיקה',
    displayName: 'סטטיסטיקה',
    emoji: '📉',
    paper: '582',
    weight: 'standard',
    appearsIn: 'בכמחצית מהבגרויות',
    typicalPoints: '15-25',
    examStyle: 'התפלגות נורמלית, ציון $Z$, מרווח סמך, פירוש סטטיסטי.',
  },
  {
    key: 'מספרים מרוכבים',
    displayName: 'מספרים מרוכבים',
    emoji: 'ℂ',
    paper: '582',
    weight: 'optional',
    appearsIn: 'אופציונלי',
    typicalPoints: '15-25',
    examStyle: 'הצגה אלגברית/קוטבית, דה-מואבר, שורשי יחידה, גאומטריה במישור מרוכב.',
  },
];

/**
 * Canonical curriculum — שאלון 581 first (algebra is the foundation),
 * then 582. Within each paper, ordered by pedagogical learning sequence
 * (foundation topics first, applications last).
 */
export const MATH5_CURRICULUM: TopicMapping[] = [...PAPER_581, ...PAPER_582];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Lookup the curriculum entry for a given topic. */
export function getTopicMapping(topic: string): TopicMapping | null {
  return MATH5_CURRICULUM.find((t) => t.key === topic) ?? null;
}

/** All topics belonging to a paper, in canonical order. */
export function topicsByPaper(paper: BagrutPaper): TopicMapping[] {
  return MATH5_CURRICULUM.filter((t) => t.paper === paper);
}

/** Returns the canonical index (0-based) of a topic in the curriculum.
 *  Useful for sorting any user-defined list back into bagrut order. */
export function curriculumIndex(topic: string): number {
  const i = MATH5_CURRICULUM.findIndex((t) => t.key === topic);
  return i === -1 ? Infinity : i;
}

/** Short label like "שאלון 581" — used by the BagrutBadge component. */
export function paperLabel(paper: BagrutPaper): string {
  return `שאלון ${paper}`;
}
