import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'בגרות בכיס',
    short_name: 'בגרות בכיס',
    description: 'תרגול חכם של שאלות בגרות אמיתיות, נוצרות בזמן אמת ע״י בינה מלאכותית. הסבר מיידי לכל תשובה.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#020617',
    theme_color: '#a855f7',
    lang: 'he',
    dir: 'rtl',
    categories: ['education', 'productivity'],
    icons: [
      {
        // SVG (vector) — best quality where supported
        src: '/icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'any',
      },
      {
        // 192x192 PNG generated by app/icon.tsx (id "192")
        src: '/icon/192',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        // 512x512 PNG generated by app/icon.tsx (id "512")
        src: '/icon/512',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        // Maskable variant — full-bleed background for Android adaptive icons
        src: '/icon/maskable',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
