// ============================================================
// concept-prompt.ts — the "בוחן מושגים" generation prompt.
//
// SINGLE SOURCE. This prompt used to exist twice, in
// app/api/questions/route.ts and scripts/generate-pool.ts, with a comment in
// the second saying it "mirrors" the first — i.e. a standing invitation to
// drift. Both now import from here.
//
// Only reached for topics with NO static bank; math5 serves 252 pre-authored
// questions at $0 and never gets here.
// ============================================================

import type { ConceptLevel } from '@/content/concept-quiz/types';
import type { UnitLevel } from '@/lib/agents/config';
import type { Kind } from '@/lib/question-pool';

/** Human label for the student's unit level, in CURRENT שאלון numbering.
 *  The old prompt derived this from the subject key and said "581/582" —
 *  schools moved to 571/572, and the subject key can't tell you that a math5
 *  student is 5 units while a math4 student is 4. */
function unitsLabel(unitLevel: UnitLevel): string {
  if (unitLevel === 5) return '5 יחידות (שאלונים 571/572)';
  if (unitLevel === 4) return '4 יחידות';
  return '3 יחידות';
}

/** The SAME three definitions the human authoring brief uses, so a generated
 *  question and a hand-authored one at the same level mean the same thing. */
function levelBlock(level: ConceptLevel): string {
  if (level === 1) {
    return `רמת השאלות: **רמה 1 — מושגי בסיס**.
כל שאלה נענית מהגדרה, מניסוח של כלל, או מעובדה על תחום/טווח, עם היותר הצבה אחת.
נפתרת בראש תוך פחות מ-30 שניות, בלי דף.
שלושת המסיחים הם התפיסות השגויות הקלאסיות לאותו כלל בדיוק (השמטת גורם פנימי, היפוך כיוון בין גזירה לאינטגרל, ייבוא תחום של פונקציה אחרת, היפוך סימן).`;
  }
  if (level === 2) {
    return `רמת השאלות: **רמה 2 — יישום**.
שני צעדים משורשרים, או צעד אחד בתוספת תנאי או פיצול למקרים. נפתרת תוך פחות מ-90 שניות עם דף טיוטה.
לדוגמה: אסימפטוטה אנכית של $f(x)=\\frac{e^x-1}{e^x-4}$ — לאפס את המכנה **וגם** לפתור $e^x=4$.
המסיחים הם התוצאה של ביצוע רק אחד משני הצעדים, או ביצועם בסדר הפוך.`;
  }
  return `רמת השאלות: **רמה 3 — ברמת בגרות**.
עדיין שאלה רב-ברירתית עם 4 אפשרויות, אבל הגזע הוא מצב בגרות אמיתי — מהסוג שהיה סעיף בשאלה אמיתית — שהתשובה שלו היא אובייקט אחד שניתן להציע: ערך, תחום, משוואה, נקודה או יחס.
3-4 צעדים משורשרים, לרוב עם פרמטר.
השאלה חייבת לשבת ב**סוף** השרשרת: בקשה לצעד הראשון בלבד היא רמה 2, לא רמה 3.
כל ארבע האפשרויות חייבות להיות נקודות-סיום סבירות של מסלול פתרון (שגוי) אמיתי — אסור מספרים אבסורדיים שתלמיד יכול לפסול במבט.`;
}

export function buildConceptPrompt(
  subject: string,
  topic: string,
  level: ConceptLevel | null,
  unitLevel: UnitLevel,
  subjectPrompt?: (t: string) => string,
): string {
  const hintRule = `לכל שאלה הוסף שדה hint — רמז אחד שמכוון לכלל או לצעד הראשון, **בלי לחשוף את התשובה**.`;

  if (subject === 'math5' || subject === 'math4') {
    const base = `אתה מורה פרטי מומחה למתמטיקה ברמת ${unitsLabel(unitLevel)}. צור בדיוק 5 שאלות מושגים רב-ברירתיות (MCQ) בנושא: ${topic}.
זהו "בוחן מושגים" — לא סימולציית בגרות מלאה. המטרה: לבדוק הבנה ושליטה בכללים.`;

    // No level on the wire = an older cached client. Emit the original text
    // unchanged rather than guessing, so nothing regresses for them.
    if (level === null) {
      return `${base}
כל שאלה צריכה להיפתר בראש תוך פחות מדקה, ולהתמקד באחד מאלה:
- הגדרות ותנאים (למשל: "מתי מוגדרת $f(x)=\\ln(x-2)$?", "מהו תחום ההגדרה של...")
- אסימפטוטות והתנהגות בקצוות (למשל: "מהי האסימפטוטה האופקית של...")
- כללי גזירה ואינטגרציה (למשל: "מהי הנגזרת של $\\ln x$?", "איזה מהבאים שווה ל-$\\int e^{2x}\\,dx$?")
- זהויות, משפטים ותכונות (טריגונומטריה, מרוכבים, וקטורים, הסתברות — לפי הנושא)
- זיהוי מקרה-גבול או תפיסה שגויה נפוצה
הימנע משאלות עם חישוב ארוך רב-שלבי. התשובות המוטעות צריכות לשקף טעויות מושגיות נפוצות שתלמידים עושים.
${hintRule}`;
    }

    return `${base}

${levelBlock(level)}

התשובות המוטעות צריכות לשקף טעויות מושגיות נפוצות שתלמידים עושים — לא מספרים שרירותיים.
${hintRule}`;
  }

  const info = subjectPrompt ? subjectPrompt(topic) : '';
  return `${info}
התמקד בשאלות מושג קצרות (הגדרות, עקרונות, זיהוי) שנפתרות במהירות — לא בשאלות ארוכות.
${hintRule}`;
}

/**
 * Pool bucket for a concept request. The level MUST be part of the key: with a
 * single 'concept' bucket, a level-3 request would be served a pooled row that
 * was generated for level 1, which is worse than generating fresh.
 *
 * `kind` is a text column, so this needs no Supabase migration. Existing
 * kind='concept' rows simply become unreachable — correct, since they were
 * generated by the level-less prompt and their level is unknown.
 */
export function conceptPoolKind(level: ConceptLevel | null): Kind {
  return level ? (`concept-l${level}` as Kind) : 'concept';
}
