// GENERATED by `npx tsx scripts/_prob-extra-check.ts all --write-order`; do not edit by hand.
//
// The order a student meets the הסתברות questions in, easiest first inside every
// rung and on every 🎓 rung (owner, 2026-09-14: "חשוב מאוד העליה ההדרגתית של רמת
// הקושי בין כל השאלות"). Ranked by the gate's difficulty score; an id missing
// from this list keeps its authoring position after the ranked ones.
export const PROB_ORDER: string[] = [
];
