/**
 * _write-tf-figures.ts — generate the figures module for the trig-functions
 * stages from the verified specs.
 *
 *   npx tsx scripts/_write-tf-figures.ts
 *
 * The SVG bodies are never pasted by hand: they are emitted from
 * `_tf-figure-specs.ts`, whose assertions have already been checked against the
 * same functions. Re-run this after changing any spec, and the content picks up
 * the new coordinates with no chance of the picture drifting from the claims.
 */
import { writeFileSync } from 'fs';
import { render } from './_gen-rq-figures';
import { TF_FIGURES } from './_tf-figure-specs';

const OUT = 'content/lessons/math5/trig-functions/figures.ts';

const header = `// ============================================================
// GENERATED by scripts/_write-tf-figures.ts — do not edit by hand.
// ============================================================
//
// Every curve is sampled from the real function in scripts/_tf-figure-specs.ts,
// where each figure is paired with assertions re-derived from that same
// function. Re-run the writer after changing a spec.
//
// Hebrew is deliberately absent from the SVG — there is no bidi there. The
// Hebrew lives in each diagram's \`caption\`, which runs through MathText.
`;

const body = Object.entries(TF_FIGURES)
  .map(([id, fig]) => {
    const svg = render(fig).split('\\').join('\\\\').split('`').join('\\`').split('${').join('\\${');
    return `export const ${id}_FIGURE = \`${svg}\`;`;
  })
  .join('\n\n');

writeFileSync(OUT, `${header}\n${body}\n`, 'utf8');
console.log(`wrote ${OUT} — ${Object.keys(TF_FIGURES).length} figure(s)`);

export {};
