/**
 * build-faq-signatures.ts — record what each banked unit's answers were
 * written against, and find the ones whose exercise has since changed.
 *
 *   npx tsx scripts/build-faq-signatures.ts          # rewrite content/tutor-faq/signatures.ts
 *   npx tsx scripts/build-faq-signatures.ts --check  # report stale units; exit 1 only when a
 *                                                    # banked unit has NO signature (build not run)
 *
 * A stale unit serves nothing from its own bank (lib/tutor-faq isUnitCurrent)
 * and is handed out again by audit-tutor-faq. Run the build after every
 * banking round; run --check in `npm run check` so an edited question is seen.
 */
import { writeFileSync } from 'node:fs';
import { faqBankKeys, loadFaqBank } from '../content/tutor-faq';
import { unitSignature } from '../lib/tutor-faq';
import { FAQ_SIGNATURES } from '../content/tutor-faq/signatures';
import { allScreens } from './_screens';

const CHECK = process.argv.includes('--check');
const OUT = 'content/tutor-faq/signatures.ts';

async function main() {
  const screens = allScreens();
  const next: Record<string, number> = {};
  const stale: string[] = [];
  const unsigned: string[] = [];
  const orphan: string[] = [];
  let banked = 0;

  for (const [subject, topic] of faqBankKeys()) {
    const bank = await loadFaqBank(subject, topic);
    for (const unit of Object.keys(bank ?? {})) {
      banked++;
      const s = screens.get(unit);
      if (!s) {
        orphan.push(unit);
        continue;
      }
      const sig = unitSignature(s.question);
      next[unit] = sig;
      const recorded = (FAQ_SIGNATURES as Record<string, number>)[unit];
      if (recorded === undefined) unsigned.push(unit);
      else if (recorded !== sig) stale.push(unit);
    }
  }

  console.log(`${banked} banked units · ${stale.length} stale · ${unsigned.length} unsigned · ${orphan.length} not on any screen`);
  if (stale.length) console.log(`⚠ stale (edited since banking, served from the model until re-banked):\n  ${stale.join('\n  ')}`);
  if (orphan.length) console.log(`⚠ banked but no screen publishes them (retired or renumbered ids):\n  ${orphan.slice(0, 20).join('\n  ')}${orphan.length > 20 ? '\n  …' : ''}`);

  if (CHECK) {
    if (unsigned.length) {
      console.log(`⛔ ${unsigned.length} banked units have no signature — run: npx tsx scripts/build-faq-signatures.ts\n  ${unsigned.slice(0, 10).join('\n  ')}`);
      process.exit(1);
    }
    return;
  }

  const body =
    `// GENERATED by scripts/build-faq-signatures.ts — do not edit.\n` +
    `// unit id → fingerprint of the question + solution its FAQ bank was written against.\n` +
    `export const FAQ_SIGNATURES: Record<string, number> = ${JSON.stringify(next, Object.keys(next).sort(), 0)};\n`;
  writeFileSync(OUT, body, 'utf8');
  console.log(`wrote ${Object.keys(next).length} signatures → ${OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
